### PR TITLE
Add PhpMyAdmin & PhpMemcacheAdmin

### PR DESCRIPTION
**Pull request by vzool**
Hi,
I like this box, and I add important tools for fast debugging & development which are they:
- PhpMyAdmin at http://192.168.33.10:8888/phpmyadmin

User name: phpmyadmin

Password: vagrant
- PhpMemcacheAdmin at http://192.168.33.10:8888/phpmemcacheadmin

In fact, it is not stick to IP Address(192.168.33.10), because it's dynamic(0.0.0.0)

Hope you like it guys, Salam

### CODE REVIEW

**Comment by drawcard** [comment]
I'm not sure if it's Scotchbox's intention to have PHPMyAdmin as a default, they are encouraging the use of a desktop client instead. From the homepage:

> From a Desktop Client
You'll need to download either Sequel Pro or Navicat or some other desktop database client. **Switching to one of these from phpMyAdmin will be a life changing experience so just do it already**. 

It's also really easy for anyone to [set up PHPMyAdmin](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-14-04) themselves if they really have to.

**Comment by vzool** [comment]
@drawcard Yeah I know, but in general Vagrant boxes were made to save time and energy.
All developers are looking for **Zero Configuration Box** with all **App Dev Tools** required for the project.
Peace Man...

**Comment by drawcard** [comment]
Don't get me wrong, it is a good idea, but developers are also interested in a clean box that doesn't require the manual uninstallation of anything that you wouldn't normally find on a clean server. I'm not involved in the project anyway but am just giving my opinion as another user. No harsh criticism intended 😄 👍

**Comment by digitalpenguin** [comment]
Would absolutely love it for PHPMyAdmin to be included. It's the main thing missing.

**Comment by maxpou** [comment]
Please don't. It's so easy to install.

```bash
cd /var/www/public
git clone --depth=1 --branch=master https://github.com/phpmyadmin/phpmyadmin pma
# optionnal
rm -rf pma/.git
```

That it !

**Comment by jeancabral** [comment]
Hi guys,

How to connect to the database using Navicat? I have to set up a port redirection for this? I add in /etc /hosts only the alias my.app for 192.168.33.10. 

(Sorry my english)

**Comment by drawcard** [comment]
There are instructions at https://box.scotch.io/ under the heading "From a Desktop Client"

**Comment by whatnickcodes** [comment]
We are encouraging desktop client because it's slimmer and also makes you a better developer (IMHO at least).

I will add install steps to the box though for people who like this

**Comment by drawcard** [comment]
Since you guys recommended using Sequel Pro on your instruction page, I haven't looked back!

**Pull request closed without merging**
