### PR TITLE
Make files executable too

### PR DESCRIPTION
**Pull request by mariosant**
There are some CMS' that have a cli tool as well. This makes it easier to execute it.

### CODE REVIEW

**Comment by mariosant** [comment]
I don't really like making everything executable, but since fmode` option was there, I didn't want to remove it. What do you guys think?

**Comment by ncerminara** [comment]
Hey @mariosant I'm not going to merge this change. I don't think any other popular stacks do this

**Comment by mariosant** [comment]
@ncerminara, WordPress has wp-cli, Drupal has drush, October CMS has its own and Grav CMS as well, just to name a few.

I understand that my solution is kinda ugly, but the fact is that is sometimes helpful to have executable files in the project directory.

Should I open an issue instead or you think that it is a bad idea anyway?

**Comment by ncerminara** [comment]
WP-CLI is installed. Just do:

```
vagrant ssh
wp-cli XXX
```

It works already

**Comment by mariosant** [comment]
Thanks for that. It sounds that non wp users, should edit the Vagrantfile as they need.

**Comment by ncerminara** [comment]
What exactly are you trying to accomplish by making everything writable? Which CLI tool?

Does not work:

```
vagrant ssh
# Command to install CLI tool on Ubuntu
```

**Comment by mariosant** [comment]
Well, my personal use case is the following:

I am a fan of [Grav CMS](http://www.getgravcms.org). Grav comes with a couple very useful tools, a package manager called GPM and a utility for performing some administration tasks.

In order to execute any of them, I should ssh into the VM, go to the project folder and run it from there.

```
$ ./bin/gpm 
-or-
$ ./bin/grav
```

This requires both of those files to be executable. I currently solve this issue, by passing an `fmode=777` option.

To answer your last question, these tools are part of the standard cms installation.

**Pull request closed without merging**
